import { onAuthStateChanged } from "firebase/auth";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import ChatView from "../components/ChatView";
import Menu from "../components/Menu";
import { auth } from "../lib/firebase";
import { Box, Button, Slide } from "@chakra-ui/react";
import { useAuth } from "../context/AuthContext";
import UserInfoBar from "../components/UserInfoBar";
const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Chat App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box h="100vh" display="flex">
				<Box
					w={{ base: "full", md: "40%" }}
					h="full"
					position={{ base: "fixed", md: "relative" }}
					top={0}
					left={0}
					zIndex={10}
					className={`transition-transform duration-300 ${
						null !== null ? "-translate-x-full" : "translate-x-0"
					} md:translate-x-0`}
					display="flex"
					flexDirection="column"
					justifyContent="space-between"
				>
					<Box>Left</Box>
					<UserInfoBar />
				</Box>
				<Box
					w={{ base: "full" }}
					h="full"
					position={{ base: "fixed", md: "relative" }}
					top={0}
					left={0}
					zIndex={10}
					bg="blackAlpha.400"
					className={`transition-transform duration-300 ${
						null !== null ? "translate-x-0" : "translate-x-full"
					} md:translate-x-0`}
				>
					<Box>Open or start a new conversation</Box>
				</Box>
			</Box>
		</div>
	);
};

export default Home;
